[SER-382] Import Platform Unity_States binary
tomthecarrot/constellation pull request #108
Opened 2022-07-22 23:22 UTC by tomthecarrot

2022-07-22 23:22 UTC, tomthecarrot commented on demos/unity_states/unity/Assets/Plugins/unity_states
> +../../../cs/bin/Debug/netstandard2.1
This is a symlink

2022-07-22 23:46 UTC, TheButlah commented
Stamping without real review in the interest of time, and because I don't know unity and will have to experiment on monday.

2022-07-22 23:47 UTC, TheButlah requested changes
edit: dll needs to be gitignored

2022-07-22 23:50 UTC, tomthecarrot commented
> edit: dll needs to be gitignored

This DLL was intentionally checked in since it's not in the symlinked directory. Will symlink just the DLL and re-request.

2022-07-23 17:02 UTC, TheButlah approved these changes

2022-07-23 17:02 UTC, merged