[SER-469] Separate example contract into its own crate
tomthecarrot/constellation pull request #143
Opened 2022-10-13 21:45 UTC by TheButlah

2022-10-24 22:08 UTC, tomthecarrot requested changes
Great work! Tests pass on my Mac.

2022-10-24 22:08 UTC, tomthecarrot commented on demos/unity_states/rust/Cargo.toml
> +crate-type = ["cdylib"]
[Suggestion]
We still need a static lib to be generated for cross-compilation to iOS.

2022-10-24 22:08 UTC, tomthecarrot commented on client/codegen_pinvoke/Main.cs
> +            // No need to copy if the output name is the same as the input
Good call. I made the same addition in a WIP branch a few days ago locally during development of [MKE-955] 😅 I should have PR'd it then to avoid you having to do the same.

2022-10-24 22:08 UTC, tomthecarrot commented on client/contract_example/cs/src/ExampleContract.cs
> +        public ObjectHandle ObjectCreate(Baseline baseline, byte u8_0, byte u8_1, sbyte i8_0, sbyte i8_1, float f32_0, float f32_1, RString str_0)
Ditto WIP branch comment.

2022-10-24 22:08 UTC, tomthecarrot commented on client/contract_example/cs/src/ExampleContract.cs
> +using generated = tp_contract_example.generated.__Internal;
[General Thought]
Now I see why you had to restart the Mac so often with the Rosetta 2 error 
![image](https://user-images.githubusercontent.com/5103968/197639023-f0eae086-45b7-4f4a-aa98-0392b94da1fb.png)

2022-10-25 09:07 UTC, TheButlah commented on demos/unity_states/rust/Cargo.toml
> +crate-type = ["cdylib"]
ah thank you, this change can be reverted, it was from local testing

2022-10-25 09:08 UTC, TheButlah commented on client/contract_example/cs/src/ExampleContract.cs
> +using generated = tp_contract_example.generated.__Internal;
why is that?

2022-10-25 09:11 UTC, TheButlah commented on demos/unity_states/rust/Cargo.toml
> +crate-type = ["cdylib"]
fixed

2022-10-25 15:53 UTC, tomthecarrot commented on client/contract_example/cs/src/ExampleContract.cs
> +using generated = tp_contract_example.generated.__Internal;
Because there are many changes to the C# code.

2022-10-25 15:53 UTC, tomthecarrot approved these changes

2022-10-25 15:53 UTC, merged